name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  build:
    uses: sivaprasadreddy/reusable-github-workflows/.github/workflows/java-gradle-build-test.yml@main

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docs
        run: ./gradlew asciidoctor
